-- Confirmação na fonte (2026-09-28): páginas oficiais da Meta lidas direto (Chrome) e pelo
-- 1º Pesquisador. Espelha o que foi aplicado no banco nesse dia (idempotente).
update public.trafego_manual_itens set confianca='oficial', fonte_url='https://www.facebook.com/business/help/112167992830700', valor='~50 resultados na semana após a última edição significativa (por conjunto)', verificado_em='2026-09-28', updated_at=now() where chave='aprendizado_eventos';
update public.trafego_manual_itens set confianca='oficial', fonte_url='https://www.facebook.com/business/help/190490051321426', regra='Programação por horário (ou veiculação por menos de 1 dia) exige orçamento vitalício; não funciona com orçamento diário', verificado_em='2026-09-28', updated_at=now() where chave='dayparting_vitalicio';
update public.trafego_manual_itens set regra='Mudança máxima de orçamento por vez. A Meta NÃO publica percentual: diz que mudança de orçamento pode ou não ser "edição significativa" conforme o tamanho (US$100→101 não; US$100→1.000 provavelmente sim). 20% é prática de mercado', verificado_em='2026-09-28', updated_at=now() where chave='orcamento_mudanca_max';
update public.trafego_manual_itens set confianca='oficial', verificado_em='2026-09-28' where chave in ('alcool_idade', 'relevancia_impressoes');
update public.trafego_manual_itens set confianca='mercado', regra = regra || ' (a Meta só recomenda menos anúncios por conjunto com criativos diversos, sem número)', verificado_em='2026-09-28' where chave='criativos_por_conjunto' and regra not like '%sem número%';
insert into public.trafego_manual_itens (chave, tema, regra, valor, confianca, fonte_url, verificado_em) values
 ('edicoes_significativas', 'Fase de aprendizado', 'Sempre reiniciam o aprendizado: mudar público, criativo, evento de otimização, adicionar anúncio, pausar 7+ dias, mudar estratégia de lance. Orçamento/lance/limite: depende do tamanho da mudança', null, 'oficial', 'https://www.facebook.com/business/help/316478108955072', '2026-09-28'),
 ('categorias_especiais', 'Política', 'Categorias especiais de anúncio: produtos financeiros, emprego, moradia, temas sociais/eleições/política. Não há categoria para alimentação nem álcool', null, 'oficial', 'https://www.facebook.com/business/help/298000447747885', '2026-09-28'),
 ('capi_mensagens', 'Medição', 'Pedido vindo do WhatsApp: Conversions API for Business Messaging com action_source=business_messaging, messaging_channel=whatsapp e o ctwa_clid do clique (vem no webhook)', null, 'oficial', 'https://developers.facebook.com/docs/marketing-api/conversions-api/business-messaging/', '2026-09-28'),
 ('opportunity_score', 'Diagnóstico', 'Opportunity Score (0–100) mede quantas recomendações do Gerenciador foram aplicadas, ponderadas pelo impacto estimado; não é métrica de desempenho', null, 'oficial', 'https://www.facebook.com/business/help/804913634782260', '2026-09-28')
on conflict (chave) do nothing;
