-- =============================================================================
-- MIGRATION: grants_definitivos
-- Descricao: Aplica GRANTs permanentes em todas as tabelas do projeto
--            (substitui a edge function grant-permissions, eliminando chamadas
--             repetitivas e a dependencia da RPC insegura exec_sql)
-- Data: 2026-06-12
-- =============================================================================

-- TABELAS DO PROJETO (68 tabelas - copiadas exatamente do array "tables"
-- da edge function grant-permissions/index.ts)

-- ─── authenticated: SELECT, INSERT, UPDATE, DELETE ───────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sessions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.item_ingredients TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tenants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_tenants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.permissions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.system_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payment_methods TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.station_operators TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ingredients TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.menu_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.menu_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.item_promotions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.option_groups TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.options TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.item_preset_observations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.global_observations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recipes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.combo_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.customers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cash_registers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cash_movements TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.station_sessions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.table_sessions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.table_session_customers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_options TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_observations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_units TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.waiter_calls TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_movements TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_log TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tables TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ingredient_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.combos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_parts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kitchen_stations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kiosk_tokens TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_cash_flow TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_accounts_payable TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_purchases TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_purchase_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_cost_centers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_suppliers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_budgets TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_budget_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_bank_statements TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_dre_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_receivable_installments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_anticipations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_implementation_costs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_implementation_columns TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_investment_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_bank_accounts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_bank_transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_income_routing TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hr_employees TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hr_payroll TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.refunds TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_discounts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.promotion_rules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vouchers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.voucher_transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loyalty_transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.combo_ingredients TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ingredient_batches TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.print_queue TO authenticated;

-- ─── anon: SELECT ────────────────────────────────────────────────────────
GRANT SELECT ON public.sessions TO anon;
GRANT SELECT ON public.item_ingredients TO anon;
GRANT SELECT ON public.tenants TO anon;
GRANT SELECT ON public.user_tenants TO anon;
GRANT SELECT ON public.permissions TO anon;
GRANT SELECT ON public.system_settings TO anon;
GRANT SELECT ON public.payment_methods TO anon;
GRANT SELECT ON public.station_operators TO anon;
GRANT SELECT ON public.ingredients TO anon;
GRANT SELECT ON public.menu_categories TO anon;
GRANT SELECT ON public.menu_items TO anon;
GRANT SELECT ON public.item_promotions TO anon;
GRANT SELECT ON public.option_groups TO anon;
GRANT SELECT ON public.options TO anon;
GRANT SELECT ON public.item_preset_observations TO anon;
GRANT SELECT ON public.global_observations TO anon;
GRANT SELECT ON public.recipes TO anon;
GRANT SELECT ON public.combo_items TO anon;
GRANT SELECT ON public.customers TO anon;
GRANT SELECT ON public.cash_registers TO anon;
GRANT SELECT ON public.cash_movements TO anon;
GRANT SELECT ON public.station_sessions TO anon;
GRANT SELECT ON public.table_sessions TO anon;
GRANT SELECT ON public.table_session_customers TO anon;
GRANT SELECT ON public.orders TO anon;
GRANT SELECT ON public.order_item_options TO anon;
GRANT SELECT ON public.order_item_observations TO anon;
GRANT SELECT ON public.order_item_units TO anon;
GRANT SELECT ON public.payments TO anon;
GRANT SELECT ON public.waiter_calls TO anon;
GRANT SELECT ON public.stock_movements TO anon;
GRANT SELECT ON public.audit_log TO anon;
GRANT SELECT ON public.tables TO anon;
GRANT SELECT ON public.order_items TO anon;
GRANT SELECT ON public.ingredient_categories TO anon;
GRANT SELECT ON public.combos TO anon;
GRANT SELECT ON public.order_item_parts TO anon;
GRANT SELECT ON public.users TO anon;
GRANT SELECT ON public.kitchen_stations TO anon;
GRANT SELECT ON public.kiosk_tokens TO anon;
GRANT SELECT ON public.fin_cash_flow TO anon;
GRANT SELECT ON public.fin_accounts_payable TO anon;
GRANT SELECT ON public.fin_purchases TO anon;
GRANT SELECT ON public.fin_purchase_items TO anon;
GRANT SELECT ON public.fin_cost_centers TO anon;
GRANT SELECT ON public.fin_suppliers TO anon;
GRANT SELECT ON public.fin_budgets TO anon;
GRANT SELECT ON public.fin_budget_items TO anon;
GRANT SELECT ON public.fin_bank_statements TO anon;
GRANT SELECT ON public.fin_dre_categories TO anon;
GRANT SELECT ON public.fin_receivable_installments TO anon;
GRANT SELECT ON public.fin_anticipations TO anon;
GRANT SELECT ON public.fin_implementation_costs TO anon;
GRANT SELECT ON public.fin_implementation_columns TO anon;
GRANT SELECT ON public.fin_investment_settings TO anon;
GRANT SELECT ON public.fin_bank_accounts TO anon;
GRANT SELECT ON public.fin_bank_transactions TO anon;
GRANT SELECT ON public.fin_income_routing TO anon;
GRANT SELECT ON public.hr_employees TO anon;
GRANT SELECT ON public.hr_payroll TO anon;
GRANT SELECT ON public.refunds TO anon;
GRANT SELECT ON public.order_discounts TO anon;
GRANT SELECT ON public.promotion_rules TO anon;
GRANT SELECT ON public.vouchers TO anon;
GRANT SELECT ON public.voucher_transactions TO anon;
GRANT SELECT ON public.loyalty_transactions TO anon;
GRANT SELECT ON public.combo_ingredients TO anon;
GRANT SELECT ON public.ingredient_batches TO anon;
GRANT SELECT ON public.print_queue TO anon;

-- ─── service_role: SELECT, INSERT, UPDATE, DELETE ────────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sessions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.item_ingredients TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tenants TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_tenants TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.permissions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.system_settings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payment_methods TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.station_operators TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ingredients TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.menu_categories TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.menu_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.item_promotions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.option_groups TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.options TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.item_preset_observations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.global_observations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recipes TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.combo_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.customers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cash_registers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cash_movements TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.station_sessions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.table_sessions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.table_session_customers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_options TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_observations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_units TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.waiter_calls TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_movements TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_log TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tables TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ingredient_categories TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.combos TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_item_parts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kitchen_stations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kiosk_tokens TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_cash_flow TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_accounts_payable TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_purchases TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_purchase_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_cost_centers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_suppliers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_budgets TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_budget_items TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_bank_statements TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_dre_categories TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_receivable_installments TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_anticipations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_implementation_costs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_implementation_columns TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_investment_settings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_bank_accounts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_bank_transactions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_income_routing TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hr_employees TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hr_payroll TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.refunds TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_discounts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.promotion_rules TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vouchers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.voucher_transactions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loyalty_transactions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.combo_ingredients TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ingredient_batches TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.print_queue TO service_role;

-- ─── SEQUENCES ──────────────────────────────────────────────────────────
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;